export const works = [
  {
    id: 1,
    category: `Tech`,
    skills: [
      'HTML',
      'CSS',
      'Bootstrap',
      'MaterialUI',
      'Javascript',
      'React',
      'Node.js',
      'PHP',
      'Python',
      'Django',
      'Flask',
      'SQL',
      'Git/GitHub',
      'Postman',
      'Firebase',
      'Heroku',
      'AzureCloud',
      'VSCode',
    ],
  },
  {
    id: 2,
    category: `ORGANISATION & STRATEGIE`,
    skills: [
      'OKR',
      'vision produit',
      'réalisation de roadmap',
      'sprint planning',
      'rétrospective sprint',
      'démonstration sprint',
      'Jira',
      'Azure DevOps',
      'Trello',
      'Notion',
      'Microsoft365',
      'Google Analytics',
    ],
  },
  {
    id: 3,
    category: `COMMUNICATION & REDACTION`,
    skills: [
      'demo scrum',
      ' expression des besoins',
      ' cahier des charges',
      ' user story',
      ' manuel utilisateur',
      ' support de formation',
      ' manuel scolaire',
    ],
  },
  {
    id: 4,
    category: `Soft skills`,
    skills: [
      'sport & yoga',
      'cours part',
      'coaching',
      'relation client',
      'auto-entrepreneure',
      'accompagnement',
      'assistance',
      'dépannage des utilisateurs',
      'Pilotage de projet',
      'gestion de petite équipe',
    ],
  },
]
