export const works = [
  {
    id: 1,
    category: `Tech`,
    skills: [
      'HTML',
      'CSS',
      'Bootstrap',
      'MaterialUI',
      'Javascript',
      'React',
      'Node.js',
      'PHP',
      'Python',
      'Django',
      'Flask',
      'SQL',
      'Git/GitHub',
      'Postman',
      'Firebase',
      'Heroku',
      'AzureCloud',
      'VSCode',
    ],
  },
  {
    id: 2,
    category: `ORGANISATION & STRATEGIE`,
    skills: [
      'gestion de projet',
      "gestion d`'équipe",
      'OKR',
      'vision produit',
      'roadmap',
      'sprint planning',
      'rétrospective sprint',
      'démonstration sprint',
      'Jira',
      'Azure DevOps',
      'Trello',
      'Notion',
      'Microsoft365',
      'Google Analytics',
    ],
  },
  {
    id: 3,
    category: `COMMUNICATION & REDACTION`,
    skills: [
      'support demo',
      'specifications fonctionnelles',
      'expression des besoins',
      'cahier des charges',
      'user story',
      'manuel utilisateur',
      'support de formation',
      'manuel scolaire',
    ],
  },
  {
    id: 4,
    category: `TRANSVERSE`,
    skills: [
      'yoga',
      "animation d'atelier web",
      'coaching',
      'auto-entrepreneure',
      'pédagogue',
      'bienveillante',
      'autodidacte',
      'patiente',
    ],
  },
]
