export const experiences = [
  {
    id: 1,
    type: 1,
    period: 'depuis 2019',
    company: 'freelance',
    website: '',
    title: 'DEVELOPPEUSE WEB FREELANCE',
    description: [
      `Création d'application web (SaaS) sur mesure répondant aux besoins de diverses PME entammant leur transformation digitale (BTP, organismes de formation).`,
      `Analyse des besoins et de l'existant, développement en mode agile.`,
    ],
  },
  {
    id: 2,
    type: 1,
    period: '2020 - 2021',
    company: 'So App',
    website: 'https://www.so-app.fr/',
    title: 'CONSULTANTE EN TRANSFORMATION DIGITALE\n & DEVELOPPEUSE WEB',
    description: [
      `Stratégie et mise en place de la transformation interne, définition et optimisation de process.`,
      `Redéfinition des Vision et Mission de l'entreprise. Digitalisation de la relation client et fournisseur.`,
      `Conseil et accompagnement en Stratégie de développement.`,
      `Conseil en transformation digitale des clients (associations et organismes de formation).`,
      `Tech : refonte totale de l'outil de gestion interne (SaaS)`,
    ],
  },
  {
    id: 3,
    type: 1,
    period: '2019 - 2020',
    company: 'Europcar Mobility Group',
    website: 'https://europcar-mobility-group.com/',
    title: 'PRODUCT OWNER',
    description: [
      `Rôle de product owner au sein d'une Product Team. Rédaction de User Stories et priorisation du backlog.`,
      `Application de la méthodologie Scrum, puis Kanban.`,
      `Travail en collaboration avec les Business Owner, UX/UI designer.`,
      `Organisation d'atelier (vision produit, storymapping, atelier client).`,
      `Définition de KPI, mise en place et suivi du tracking. Suivi des livraisons, applications internes & applications B2C (web & mobile).`,
    ],
  },
  {
    id: 4,
    type: 1,
    period: '2018 - 2019',
    company: 'Innovative Digital Technologies',
    website: 'https://www.idt.pf/',
    title: 'PRODUCT OWNER & SCRUM MASTER',
    description: [
      `Analyse des besoins client, rédaction de dossier d'expression des besoins, modélisation des processus métier, rédaction de spécificités fonctionnelles & User Stories définition et
        conception d'applications web sur-mesure, modélisation du modèle de données, gestion de projets en méthodologie Agile (Scrum).`,
      `Suivi du développement, livraisons, tests, déploiement, phase pilote, ateliers clients, formations, documentation, communication et
        retour sur investissement.`,
      `Rôle de scrum master & product owner.`,
    ],
  },
  {
    id: 5,
    type: 1,
    period: '2010 - 2017',
    company: 'Leos',
    website: 'https://www.leos.fr/',
    title: 'DEVELOPPEUSE WEB & CHEF DE PROJET',
    description: [
      `Analyse et traduction des besoins des clients, rédaction de cahiers des charges, conception et maintenance de bases de données (MySQL), développement et déploiement
        d'application web sur-mesure de type intranet, ERP, GED (PHP) orientée EdTech.`,
      `Création de sites internet, rédaction de manuel utilisateur et tutoriel, support utilisateur, formation en clientèle.`,
      `Création et mise en place d'outils de gestion interne (prospection, gestion financière, pilotage des projets, communication, suivi des demandes, statistiques)`,
    ],
  },
  {
    id: 6,
    type: 2,
    period: '2009 - 2010',
    company: 'Lycée Gaston Bachelard, Chelles (77)',
    website: 'http://www.lyceebachelardchelles.fr/',
    title: 'ASSISTANTE PEDAGOGIQUE PHYSIQUE-CHIMIE',
    description: [
      `Cours supplémentaires de soutien aux élèves en difficulté ou volontaires en Physique-Chimie.`,
      `Aide aux devoirs et à la préparation des examens en Mathématiques, Physique-Chimie et SVT.`,
      `Niveau lycée général et technologique.`,
    ],
  },
  {
    id: 7,
    type: 2,
    period: '2005 - 2007',
    company: 'Profadom',
    website: 'https://cours-legendre.fr/',
    title: 'ENSEIGNANTE VACATAIRE',
    description: [
      `Soutien scolaire, cours particulier à domicile, matière scientifiques (Mathématiques, Physique-Chimie et SVT), niveau collège et lycée.`,
    ],
  },
  {
    id: 8,
    type: 2,
    period: '2007 - 2011',
    company: 'Complétude',
    website: 'https://www.completude.com/',
    title: 'ENSEIGNANTE VACATAIRE & REDACTRICE DE MANUEL',
    description: [
      `Soutien scolaire, cours particulier à domicile, matière scientifiques (Mathématiques, Physique-Chimie et SVT), niveau collège et lycée.`,
      `Animation de stage intensif en petit groupe : remise à niveau, préparation des examens.`,
      `Rédaction de manuel scolaire (Mathématique, Physique-Chimie).`,
    ],
  },
  {
    id: 9,
    type: 2,
    period: '2019',
    company: 'Moonkeys',
    website: 'https://www.moonkeys-education.com/',
    title: 'ANIMATRICE ATELIER CODING',
    description: [
      `Préparation et animation d'ateliers et de stages en petit groupe.`,
      `Sensibilisation et enseignement de l'algorithmie autour du jeu (Scratch).`,
      `Initiation à la programmation et à la robotique.`,
      `Public : enfants de 7 à 12 ans.`,
    ],
  },
]
